"""initial opscontrol schema"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision="0001_initial"
down_revision=None
branch_labels=None
depends_on=None
execution_type=sa.Enum("SCHEDULED","MANUAL",name="executiontype")
execution_status=sa.Enum("SUCCESS","FAILED","RUNNING","LONG_RUNNING","NO_RUN","NO_RESPONSE",name="executionstatus")
investigation_status=sa.Enum("NEW","ACKNOWLEDGED","INVESTIGATING","ROOT_CAUSE_IDENTIFIED","RECOVERY_IN_PROGRESS","MONITORING","RESOLVED",name="investigationstatus")
def upgrade():
    bind=op.get_bind()
    execution_type.create(bind,checkfirst=True);execution_status.create(bind,checkfirst=True);investigation_status.create(bind,checkfirst=True)
    op.create_table("organizations",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("name",sa.String(200),nullable=False,unique=True),sa.Column("code",sa.String(50),nullable=False,unique=True),sa.Column("active",sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False))
    op.create_table("vms",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("organization_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("organizations.id"),nullable=False),sa.Column("hostname",sa.String(200),nullable=False),sa.Column("environment",sa.String(50),nullable=False),sa.Column("os",sa.String(100)),sa.Column("monitoring_enabled",sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("organization_id","hostname",name="uq_vm_org_hostname"))
    op.create_index("ix_vms_organization_id","vms",["organization_id"])
    op.create_table("applications",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("vm_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("vms.id"),nullable=False),sa.Column("name",sa.String(200),nullable=False),sa.Column("app_type",sa.String(100)),sa.Column("monitoring_enabled",sa.Boolean(),nullable=False,server_default=sa.true()),sa.UniqueConstraint("vm_id","name",name="uq_application_vm_name"))
    op.create_table("pentaho_instances",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("vm_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("vms.id"),nullable=False),sa.Column("name",sa.String(200),nullable=False),sa.Column("base_url",sa.String(500)),sa.Column("repository_name",sa.String(200)),sa.Column("active",sa.Boolean(),nullable=False,server_default=sa.true()))
    op.create_table("job_orders",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("organization_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("organizations.id"),nullable=False),sa.Column("vm_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("vms.id"),nullable=False),sa.Column("pentaho_instance_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("pentaho_instances.id")),sa.Column("name",sa.String(200),nullable=False),sa.Column("environment",sa.String(50),nullable=False),sa.Column("active",sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column("expected_runtime_seconds",sa.Integer()),sa.Column("sla_seconds",sa.Integer()),sa.Column("schedule",sa.JSON()),sa.Column("expected_window_start",sa.String(10)),sa.Column("expected_window_end",sa.String(10)),sa.Column("no_run_grace_seconds",sa.Integer()),sa.Column("monitoring_enabled",sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("organization_id","vm_id","name",name="uq_job_order_identity"))
    op.create_table("job_order_histories",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("job_order_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("job_orders.id"),nullable=False),sa.Column("execution_type",execution_type,nullable=False),sa.Column("status",execution_status,nullable=False),sa.Column("started_at",sa.DateTime(timezone=True)),sa.Column("ended_at",sa.DateTime(timezone=True)),sa.Column("detected_at",sa.DateTime(timezone=True)),sa.Column("expected_runtime_seconds",sa.Integer()),sa.Column("sla_seconds",sa.Integer()),sa.Column("sla_status",sa.String(50)),sa.Column("failed_step",sa.String(200)),sa.Column("source_error_code",sa.String(100)),sa.Column("source_error_message",sa.Text()),sa.Column("source_exception",sa.Text()),sa.Column("source_log_location",sa.String(1000)),sa.Column("source_result",sa.String(200)),sa.Column("incident_number",sa.String(100)),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
    op.create_index("ix_job_order_histories_job_order_id","job_order_histories",["job_order_id"])
    op.create_table("job_step_executions",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("history_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("job_order_histories.id"),nullable=False),sa.Column("name",sa.String(200),nullable=False),sa.Column("step_type",sa.String(100)),sa.Column("status",sa.String(50),nullable=False),sa.Column("started_at",sa.DateTime(timezone=True)),sa.Column("ended_at",sa.DateTime(timezone=True)),sa.Column("duration_seconds",sa.Integer()),sa.Column("records_read",sa.Integer()),sa.Column("records_written",sa.Integer()),sa.Column("records_rejected",sa.Integer()),sa.Column("error_code",sa.String(100)),sa.Column("error_message",sa.Text()))
    op.create_index("ix_job_step_executions_history_id","job_step_executions",["history_id"])
    op.create_table("investigations",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("history_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("job_order_histories.id"),nullable=False,unique=True),sa.Column("status",investigation_status,nullable=False),sa.Column("operator",sa.String(200)),sa.Column("started_at",sa.DateTime(timezone=True)),sa.Column("resolved_at",sa.DateTime(timezone=True)),sa.Column("failure_category",sa.String(100)),sa.Column("suspected_cause",sa.Text()),sa.Column("confidence",sa.String(50)),sa.Column("root_cause",sa.Text()),sa.Column("root_cause_status",sa.String(50)))
    op.create_table("investigation_transitions",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("investigation_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("investigations.id"),nullable=False),sa.Column("previous_status",investigation_status,nullable=False),sa.Column("new_status",investigation_status,nullable=False),sa.Column("operator",sa.String(200),nullable=False),sa.Column("comment",sa.Text()),sa.Column("timestamp",sa.DateTime(timezone=True),nullable=False))
    op.create_index("ix_investigation_transitions_investigation_id","investigation_transitions",["investigation_id"])
    op.create_table("operator_notes",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("investigation_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("investigations.id"),nullable=False),sa.Column("operator",sa.String(200),nullable=False),sa.Column("text",sa.Text(),nullable=False),sa.Column("evidence_reference",sa.String(1000)),sa.Column("timestamp",sa.DateTime(timezone=True),nullable=False))
    op.create_index("ix_operator_notes_investigation_id","operator_notes",["investigation_id"])
    op.create_table("alert_incident_events",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("history_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("job_order_histories.id"),nullable=False),sa.Column("event_type",sa.String(100),nullable=False),sa.Column("source",sa.String(100),nullable=False),sa.Column("reference",sa.String(200)),sa.Column("severity",sa.String(50)),sa.Column("timestamp",sa.DateTime(timezone=True),nullable=False))
    op.create_index("ix_alert_incident_events_history_id","alert_incident_events",["history_id"])
def downgrade():
    for table in ["alert_incident_events","operator_notes","investigation_transitions","investigations","job_step_executions","job_order_histories","job_orders","pentaho_instances","applications","vms","organizations"]: op.drop_table(table)
    bind=op.get_bind();investigation_status.drop(bind,checkfirst=True);execution_status.drop(bind,checkfirst=True);execution_type.drop(bind,checkfirst=True)
